### ISSUE TITLE
[Improvement] - Possibility to specify the callback FQDN to set on the distant LNS

### ISSUE THREAD

**Issue by Paulo0o** [SoftwareAG/cumulocity-lora#109]
In some architecture, the cumulocity platform is behind a firwall or a front-end. In that case, the default callback URL set by the current connector is not relevant because the cumulocity instance is not exposed.
We would like to specify the FQDN of the callback URL of uplinks in some specific cases instead of setting the default hostname of the cumulocity instance.

**Comment by maciej-cz** [comment]
Closing due to wrong source branch.
