### ISSUE TITLE
Send a command to the device: Device parameters not visible

### ISSUE THREAD

**Issue by darno31** [SoftwareAG/cumulocity-lora#117]
When a command needs parameters to be sent to a lora device, the parameters are not visible on the UI and the plugin return an error.

![image](https://github.com/user-attachments/assets/d8617293-d8fb-4e1a-98cf-e92d0915caec)

**Comment by cpoder** [comment]
Fixed with latest version of the UI.

**Comment by phcrb** [comment]
Ok for the fix,  thanks
