### ISSUE TITLE
Support developers in handling operations with dynamic parameters

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-lora#14]
Operations can be defined to have parameters. These are shown in the UI when sending a command to a device. Actually handling a command with parameter in encode() is quite cumbersome as you have to implement converting the received string into JSON yourself. 

It would be great if the framework provided a helper function which parses the string into an object with the parameters as fields.

**Comment by cpoder** [comment]
I'm currently working on that for the Java implementation.
First codec to benefit from that enhancement will be NKE.
