### ISSUE TITLE
Device deletion from C8Y does not propagate to TTN LNS

### ISSUE THREAD

**Issue by phcrb** [SoftwareAG/cumulocity-lora#21]
From Cumulocity, device management lora application, deleting a device does not propagate to LNS

### Scenario
1. a device is provisioned in ttn LNS and pushed to C8Y, it's available in devicemanagement-lora/index.html#/lora-device
2. From the app, delete the device, selecting "Deprovision device from LoRa network server"

The device disappears from the list, but still remains in ttn end-devices list
Trigger a new data tx make it appear again in C8Y lora inventory, proving that it have not been deleted in LNS side

**Comment by cpoder** [comment]
The problem is due to the case of the dev EUI which is in lower case.
TTN expect the dev EUI to be passed as a bytestring, and default encoding expect uppercase for HEX input.
This should be solved with latest commit.

**Comment by phcrb** [comment]
Hi I've set up a new device the same way as described here. The deveui and other lora euis are all uppercased, when they arrive in C8Y, the letters in the external Id are lower cased.
After uppercasing the external id, the deletion from C8Y also  deletes the end-device in TTN
OK for your explanation

Waiting for a deployment of the framework to check your fix
@cpoder
