### ISSUE TITLE
Allow device codecs to define the device type to be used per model

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-lora#23]
At the moment always c8y_LoraDevice is used which prevents the usage of device-type-specific dashboards. The idea is to allow a codec to control for each model what device type should be used.

**Comment by cpoder** [comment]
This was changed in latest release. Now LoRa device are identified as such with the fragment lora_ns_device_LoRaDevice.
Device type can now also be set and altered from LoRa device onboarding screen.
