### ISSUE TITLE
Device provisionning from objenious to C8Y fails

### ISSUE THREAD

**Issue by phcrb** [SoftwareAG/cumulocity-lora#27]
[lora-ns-ttn-scope-t2244816-deployment-84bbd76cb9-phx8r (2).log](https://github.com/SoftwareAG/cumulocity-lora/files/6583397/lora-ns-ttn-scope-t2244816-deployment-84bbd76cb9-phx8r.2.log)
![device-objenious-TX](https://user-images.githubusercontent.com/84912886/120456451-e7b6ea80-c395-11eb-9cd9-41c9dd885923.jpg)
![device-objenious-def](https://user-images.githubusercontent.com/84912886/120456462-ea194480-c395-11eb-8eed-62b6a6dbf420.jpg)

Hi,
I set up a device in objenious frontend and trigger a data tx
It does not appear in C8Y
see attached device objenious definition and activities 
see attached lora app logs

**Comment by cpoder** [comment]
Hi,
The wrong logs are attached.
Anyway, the problem is due to null payload, which is not something expected. This can be quickly fixed.

**Comment by cpoder** [comment]
Should be fixed with current version.

**Comment by phcrb** [comment]
Hello, that works now. 
Thanks
